apiVersion: apps/v1
kind: Deployment
metadata:
  name: aetherops-api
  labels:
    app: aetherops-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aetherops-api
  template:
    metadata:
      labels:
        app: aetherops-api
    spec:
      containers:
      - name: aetherops-api
        image: ghcr.io/shahisaugat/aetherops-api:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: aetherops-config
        - secretRef:
            name: aetherops-secret
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
